from pathlib import Path
import json, runpy

ROOT=Path('.')
runpy.run_path('tools/compile_runtime_i18n_parity.py', run_name='__main__')

lp=ROOT/'website/public/locales_v10.json'
data=json.loads(lp.read_text(encoding='utf-8'))
extra={
'zh':{'share_gathering':'🪄 靈光匯聚中...','orientation_upright':'正位','orientation_reversed':'逆位','default_quote':'聽見牌面，也聽見自己。','share_downloaded_manual':'✨ 靈山紀錄已下載！\n請手動上傳至社群分享。','share_clipboard_saved':'✨ 靈光已存入剪貼簿','share_generate_again':'再次生成分享卡','seeking':'祈請中...','spread_single':'單牌指引','spread_three':'三牌時間流','spread_decision':'抉擇三牌','master_opens':'大師展開','legacy_retry_error':'大師暫時斷了聯繫，靈氣不足...','share_generate':'生成靈山分享卡','coming_soon':'即將開放','copied_link':'已複製連結','deck_gallery_label':'牌卡藝廊','deck_gallery_title':'{name}・牌卡展示','upright_meaning':'正位牌義','reversed_meaning':'逆位牌義','deck_page_title':'{name}・線上塔羅占卜','deck_creator_summary':'由 {creator} 創作・{count} 張牌','deck_count_summary':'{count} 張牌','gallery_nav':'牌卡展示','share_creator':'牌卡創作：{creator}','share_exclusive':'專屬線上占卜','deck_not_found':'找不到這副牌，可能已下架或網址有誤。'},
'en':{'share_gathering':'🪄 Gathering Mana...','orientation_upright':'Upright','orientation_reversed':'Reversed','default_quote':'Listen to the cards, and to yourself.','share_downloaded_manual':'✨ Spirit Memo downloaded!\nPlease upload it manually to share.','share_clipboard_saved':'✨ Spirit memo copied','share_generate_again':'Generate share card again','seeking':'Seeking...','spread_single':'Single Guidance','spread_three':'Three-card Timeline','spread_decision':'Decision Spread','master_opens':'The Master opens','legacy_retry_error':'Connection lost, mana insufficient...','share_generate':'Generate Spirit Memo','coming_soon':'Coming Soon','copied_link':'Link copied','deck_gallery_label':'Deck Gallery','deck_gallery_title':'{name} · Card Gallery','upright_meaning':'Upright Meaning','reversed_meaning':'Reversed Meaning','deck_page_title':'{name} · Online Tarot Reading','deck_creator_summary':'Created by {creator} · {count} cards','deck_count_summary':'{count} cards','gallery_nav':'Card Gallery','share_creator':'Cards by {creator}','share_exclusive':'Exclusive online reading','deck_not_found':'This deck could not be found; it may be unpublished or the URL may be incorrect.'},
'ja':{'share_gathering':'🪄 霊気を集めています...','orientation_upright':'正位置','orientation_reversed':'逆位置','default_quote':'カードの声と、自分の声に耳を澄ませて。','share_downloaded_manual':'✨ シェア画像を保存しました。\n手動でSNSにアップロードしてください。','share_clipboard_saved':'✨ 画像をクリップボードに保存しました','share_generate_again':'シェアカードをもう一度生成','seeking':'祈願中...','spread_single':'1枚引き','spread_three':'3枚の時間軸','spread_decision':'選択の3枚引き','master_opens':'マスターが展開します','legacy_retry_error':'接続が切れました。もう一度お試しください。','share_generate':'シェアカードを生成','coming_soon':'近日公開','copied_link':'リンクをコピーしました','deck_gallery_label':'デッキギャラリー','deck_gallery_title':'{name}・カードギャラリー','upright_meaning':'正位置の意味','reversed_meaning':'逆位置の意味','deck_page_title':'{name}・オンラインタロット占い','deck_creator_summary':'{creator} 制作・{count}枚','deck_count_summary':'{count}枚','gallery_nav':'カード展示','share_creator':'カード制作：{creator}','share_exclusive':'専用オンライン占い','deck_not_found':'このデッキは見つかりません。非公開になったか、URLが間違っている可能性があります。'},
'ko':{'share_gathering':'🪄 영기를 모으는 중...','orientation_upright':'정방향','orientation_reversed':'역방향','default_quote':'카드의 목소리와 자신의 목소리에 귀 기울이세요.','share_downloaded_manual':'✨ 공유 이미지를 저장했습니다.\n직접 SNS에 업로드해 주세요.','share_clipboard_saved':'✨ 공유 이미지를 클립보드에 저장했습니다','share_generate_again':'공유 카드 다시 만들기','seeking':'기도 중...','spread_single':'원 카드 가이드','spread_three':'3장 시간 흐름','spread_decision':'선택 3장 스프레드','master_opens':'마스터가 펼칩니다','legacy_retry_error':'연결이 끊어졌습니다. 다시 시도해 주세요.','share_generate':'공유 카드 만들기','coming_soon':'곧 공개','copied_link':'링크를 복사했습니다','deck_gallery_label':'덱 갤러리','deck_gallery_title':'{name} · 카드 갤러리','upright_meaning':'정방향 의미','reversed_meaning':'역방향 의미','deck_page_title':'{name} · 온라인 타로 리딩','deck_creator_summary':'{creator} 제작 · {count}장','deck_count_summary':'{count}장','gallery_nav':'카드 갤러리','share_creator':'카드 제작: {creator}','share_exclusive':'전용 온라인 리딩','deck_not_found':'이 덱을 찾을 수 없습니다. 비공개되었거나 URL이 잘못되었을 수 있습니다.'},
'es':{'share_gathering':'🪄 Reuniendo energía...','orientation_upright':'Derecha','orientation_reversed':'Invertida','default_quote':'Escucha a las cartas y también a ti mismo.','share_downloaded_manual':'✨ Imagen guardada.\nSúbela manualmente a tu red social para compartirla.','share_clipboard_saved':'✨ Imagen copiada al portapapeles','share_generate_again':'Generar otra tarjeta','seeking':'Consultando...','spread_single':'Guía de una carta','spread_three':'Línea temporal de tres cartas','spread_decision':'Tirada de decisión','master_opens':'El Maestro abre','legacy_retry_error':'Se perdió la conexión. Inténtalo de nuevo.','share_generate':'Generar tarjeta para compartir','coming_soon':'Próximamente','copied_link':'Enlace copiado','deck_gallery_label':'Galería del mazo','deck_gallery_title':'{name} · Galería de cartas','upright_meaning':'Significado al derecho','reversed_meaning':'Significado invertido','deck_page_title':'{name} · Lectura de Tarot en línea','deck_creator_summary':'Creado por {creator} · {count} cartas','deck_count_summary':'{count} cartas','gallery_nav':'Galería de cartas','share_creator':'Cartas de {creator}','share_exclusive':'Lectura exclusiva en línea','deck_not_found':'No se encontró este mazo; puede haber sido retirado o la URL es incorrecta.'}
}
for lang, vals in extra.items(): data[lang]['common'].update(vals)
lp.write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')

p=ROOT/'website/main.js'; s=p.read_text(encoding='utf-8')
repls={
"btn.innerText = window.currentLang === 'zh' ? '🪄 靈光匯聚中...' : '🪄 Gathering Mana...';":"btn.innerText = uiText('share_gathering', '🪄 Gathering Mana...');",
"const orientationLabel = shareOrientation === 'reversed' ? (window.currentLang === 'zh' ? '逆位' : 'Reversed') : (window.currentLang === 'zh' ? '正位' : 'Upright');":"const orientationLabel = shareOrientation === 'reversed' ? uiText('orientation_reversed', 'Reversed') : uiText('orientation_upright', 'Upright');",
"const quote = bestQuote || window.brandText('default_quote', window.currentLang === 'zh' ? '聽見牌面，也聽見自己。' : 'Listen to the cards, and to yourself.');":"const quote = bestQuote || window.brandText('default_quote', uiText('default_quote', 'Listen to the cards, and to yourself.'));",
"document.getElementById('share-date').innerText = new Date().toLocaleDateString(window.currentLang === 'zh' ? 'zh-TW' : 'en-US');":"document.getElementById('share-date').innerText = new Date().toLocaleDateString(getAILanguageTag());",
"alert(window.currentLang === 'zh' ? \"✨ 靈山紀錄已下載！\\n請手動上傳至社群分享。\" : \"✨ Spirit Memo downloaded!\\nPlease upload it manually to share.\");":"alert(uiText('share_downloaded_manual', '✨ Spirit Memo downloaded!\\nPlease upload it manually to share.'));",
"shareBtn.innerHTML = `✨ 靈光已存入剪貼簿`;":"shareBtn.innerHTML = uiText('share_clipboard_saved', '✨ Spirit memo copied');",
"shareBtn.innerHTML = `再次生成分享卡`;":"shareBtn.innerHTML = uiText('share_generate_again', 'Generate share card again');",
"const orientation = spec.orientation === 'reversed' ? (window.currentLang === 'zh' ? '逆位' : 'Reversed') : (window.currentLang === 'zh' ? '正位' : 'Upright');":"const orientation = spec.orientation === 'reversed' ? uiText('orientation_reversed', 'Reversed') : uiText('orientation_upright', 'Upright');",
"single: window.currentLang === 'zh' ? '單牌指引' : 'Single Guidance',":"single: uiText('spread_single', 'Single Guidance'),",
"three_card: window.currentLang === 'zh' ? '三牌時間流' : 'Three-card Timeline',":"three_card: uiText('spread_three', 'Three-card Timeline'),",
"decision: window.currentLang === 'zh' ? '抉擇三牌' : 'Decision Spread'":"decision: uiText('spread_decision', 'Decision Spread')",
"const prefix = `${window.currentLang === 'zh' ? '大師展開' : 'The Master opens'} <strong>【${spreadNames[spread] || spread}】</strong><br><small>${summary}</small><br>`;":"const prefix = `${uiText('master_opens', 'The Master opens')} <strong>【${spreadNames[spread] || spread}】</strong><br><small>${summary}</small><br>`;",
"const errText = window.currentLang === 'zh' ? '大師暫時斷了聯繫，靈氣不足...' : 'Connection lost, mana insufficient...';":"const errText = uiText('legacy_retry_error', 'Connection lost, mana insufficient...');",
"const btnText = window.currentLang === 'zh' ? '重新祈請' : 'Retry';":"const btnText = uiText('retry', 'Retry');",
"btn.innerText = window.currentLang === 'zh' ? '祈請中...' : 'Seeking...';":"btn.innerText = uiText('seeking', 'Seeking...');",
"btn.innerText = window.currentLang === 'zh' ? '生成靈山分享卡' : 'Generate Spirit Memo';":"btn.innerText = uiText('share_generate', 'Generate Spirit Memo');",
"window.mintNFT = () => alert(window.currentLang === 'zh' ? \"即將開放\" : \"Coming Soon\");":"window.mintNFT = () => alert(uiText('coming_soon', 'Coming Soon'));",
"btn.innerHTML = \"已複製連結\";":"btn.innerHTML = uiText('copied_link', 'Link copied');",
"if (sectionLabel) { sectionLabel.removeAttribute('data-i18n'); sectionLabel.textContent = 'Deck Gallery'; }":"if (sectionLabel) { sectionLabel.removeAttribute('data-i18n'); sectionLabel.textContent = uiText('deck_gallery_label', 'Deck Gallery'); }",
"if (sectionTitle) { sectionTitle.removeAttribute('data-i18n'); sectionTitle.textContent = `${deck.name}・牌卡展示`; }":"if (sectionTitle) { sectionTitle.removeAttribute('data-i18n'); sectionTitle.textContent = uiText('deck_gallery_title', '{name} · Card Gallery', {name: deck.name}); }",
"aria-label=\"${title} 牌義，可上下捲動\"":"aria-label=\"${uiText('card_meaning_scroll_aria', `${title} meaning, scroll vertically`, {title})}\"",
"aria-label=\"翻回牌面\">↩ 翻回牌面</button>":"aria-label=\"${uiText('card_flip_back', 'Flip to card face')}\">↩ ${uiText('card_flip_back', 'Flip to card face')}</button>",
"<div class=\"meaning-box\"><span class=\"label\">正位牌義</span><p class=\"content-text\"></p></div>":"<div class=\"meaning-box\"><span class=\"label\">${uiText('upright_meaning', 'Upright Meaning')}</span><p class=\"content-text\"></p></div>",
"${deck.reversals ? '<div class=\"ecology-box reversed-meaning\"><span class=\"label\">逆位牌義</span><p class=\"content-text\"></p></div>' : ''}":"${deck.reversals ? `<div class=\"ecology-box reversed-meaning\"><span class=\"label\">${uiText('reversed_meaning', 'Reversed Meaning')}</span><p class=\"content-text\"></p></div>` : ''}",
"document.title = `${deck.name}・線上塔羅占卜`;":"document.title = uiText('deck_page_title', '{name} · Online Tarot Reading', {name: deck.name});",
"heroSubtitle.textContent = deck.description || (deck.creator ? `由 ${deck.creator} 創作・${deck.card_count} 張牌` : `${deck.card_count} 張牌`);":"heroSubtitle.textContent = deck.description || (deck.creator ? uiText('deck_creator_summary', 'Created by {creator} · {count} cards', {creator: deck.creator, count: deck.card_count}) : uiText('deck_count_summary', '{count} cards', {count: deck.card_count}));",
"if (fortuneTitle) { fortuneTitle.removeAttribute('data-i18n'); fortuneTitle.textContent = `${deck.name}・塔羅占卜`; }":"if (fortuneTitle) { fortuneTitle.removeAttribute('data-i18n'); fortuneTitle.textContent = uiText('brand_fortune_template', '{name} · Tarot Reading', {name: deck.name}); }",
"if (fortuneLabel) { fortuneLabel.removeAttribute('data-i18n'); fortuneLabel.textContent = deck.creator ? `by ${deck.creator}` : 'Creator Tarot'; }":"if (fortuneLabel) { fortuneLabel.removeAttribute('data-i18n'); fortuneLabel.textContent = deck.creator ? `by ${deck.creator}` : uiText('creator_tarot', 'Creator Tarot'); }",
"if (galleryNav) { galleryNav.classList.remove('hidden'); galleryNav.removeAttribute('data-i18n'); galleryNav.textContent = '牌卡展示'; }":"if (galleryNav) { galleryNav.classList.remove('hidden'); galleryNav.removeAttribute('data-i18n'); galleryNav.textContent = uiText('gallery_nav', 'Card Gallery'); }",
"if (shareTag) shareTag.textContent = deck.creator ? `牌卡創作：${deck.creator}` : '專屬線上占卜';":"if (shareTag) shareTag.textContent = deck.creator ? uiText('share_creator', 'Cards by {creator}', {creator: deck.creator}) : uiText('share_exclusive', 'Exclusive online reading');",
"if (area) area.innerHTML = '<p style=\"padding:24px;text-align:center\">找不到這副牌，可能已下架或網址有誤。</p>';":"if (area) area.innerHTML = `<p style=\"padding:24px;text-align:center\">${uiText('deck_not_found', 'This deck could not be found.')}</p>`;"
}
for old,new in repls.items():
    if old in s: s=s.replace(old,new)
    else: print('WARN v2 missing', old[:90])
# Use safe localized fallback for legacy card data that only ships zh/en.
s=s.replace("card.title[window.currentLang]", "getLocalizedField(card.title)")
s=s.replace("card.meaning[window.currentLang]", "getLocalizedField(card.meaning)")
s=s.replace("currentDrawnCard.title[window.currentLang]", "getLocalizedField(currentDrawnCard.title)")
s=s.replace("currentDrawnCard.meaning[window.currentLang]", "getLocalizedField(currentDrawnCard.meaning)")
# Any duplicate modular orientation occurrence.
s=s.replace("spec.orientation === 'reversed' ? (window.currentLang === 'zh' ? '逆位' : 'Reversed') : (window.currentLang === 'zh' ? '正位' : 'Upright')", "spec.orientation === 'reversed' ? uiText('orientation_reversed', 'Reversed') : uiText('orientation_upright', 'Upright')")
p.write_text(s,encoding='utf-8')

# Strengthen the generated test's key set while retaining the no-zh/else-en rule.
t=ROOT/'website/tests/test_runtime_i18n_parity.py'
txt=t.read_text(encoding='utf-8')
txt=txt.replace("'brand_fortune_template'}", "'brand_fortune_template','share_gathering','orientation_upright','orientation_reversed','default_quote','share_downloaded_manual','share_clipboard_saved','share_generate_again','seeking','spread_single','spread_three','spread_decision','master_opens','legacy_retry_error','share_generate','coming_soon','copied_link','deck_gallery_label','deck_gallery_title','upright_meaning','reversed_meaning','deck_page_title','deck_creator_summary','deck_count_summary','gallery_nav','share_creator','share_exclusive','deck_not_found'}")
t.write_text(txt,encoding='utf-8')
